### ISSUE TITLE
`npx notios` doesn't work

### ISSUE THREAD

**Issue by hashue** [frouriojs/notios#4]
## Description

SSIA

### Error message
`/path/to/.npm/_npx/abf8cb14460754a3/node_modules/.bin/notios: 1: Syntax error: "(" unexpected`

## Environment

- **Package version:**
  
  `v0.0.0`
- **OS:**
  
  - [ ] Linux
  - [x] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v16.14.0`
- **npm version:**
  
  `8.5.3`

**Comment by LumaKernel** [comment]
直してたのでリリースした v0.0.2

原因は shebang が必須だったということです。
