### ISSUE TITLE
package.jsonのwatch

### ISSUE THREAD

**Issue by solufa** [frouriojs/notios#63]
## Description
現状は package.json 書き換えたら notios 自体を再起動しないと反映されない

npm scripts 書き換えたら自動で restart して欲しい

**Comment by LumaKernel** [comment]
リフレッシュできるようにするのは考えています。
自動リスタートは、少なくともデフォルトの挙動でそうしようとは考えていません。
やはり保存しただけで意図せず実行されるのは怖いなと思うためです。
`rm --rf ./` などと書きかけで保存してしまったり、VSCodeなどの自動セーブで実行されるのは困るかなと。
ですが、変更があった実行済みのスクリプトをわかりやすく表示するなどはありかと思っています。

**Comment by solufa** [comment]
あー確かにね
リフレッシュいいと思う

**Comment by LumaKernel** [comment]
リフレッシュほんとにいいのかはちょっと悩ましく感じる部分もあります。
起動時の情報のみに依存する現在のスタイルは、実装が簡明で、それはそれで良いのかなと思っています。

https://github.com/frouriojs/notios/blob/64143830217f7c7dea46b3406270dd8502f933df/src/entrypoints/main.ts#L11-L17

この書き方の文脈に乗るのをキープしたい。

短命のスクリプトであるという前提ということもあり、スクリプトが増えるようなことがあれば、notios自体を再起動してもらうというので統一でもいいのかなと思ったりします。

**Comment by solufa** [comment]
まあ実際のところnpm scriptsを書き換えるのはチーム内の特定の人だけだし頻度も少ない

内部実装を複雑にするコストに見合うほどのリターンがないかもなー
課題感に進展があるまでとりあえずCloseしますね、ありがとう！
