### ISSUE TITLE
マウスのスクロール(ホイール)ボタン対応

### ISSUE THREAD

**Issue by solufa** [frouriojs/notios#64]
## Description
ログ画面でスクロールボタン使えないのは思ったより不便だった・・・

**Comment by LumaKernel** [comment]
scroll-up/downキーみたいなので半ページ送りは一応実装されてます。
スクロール対応も検討中です。

**Comment by LumaKernel** [comment]
もしくは more キーバインドの d/u で半送りするとだいぶ楽かもです。(d)own/u(p) の略かな？
(スクロール対応は依然検討中です。)

**Comment by LumaKernel** [comment]
Windows の Bluetooth & devices > Mouse で "Roll the mouse wheel to scroll" と "Lines to scroll at a time" という項目がある。
wsltty(mintty)では以下のように送出されるようだった。

-  "Roll the mouse wheel to scroll" -> "Multiple lines at a time" かつ  "Lines to scroll at a time" -> 1
    - マウスホイールは上下キーを送出（区別方法なし）
-  "Roll the mouse wheel to scroll" -> "Multiple lines at a time" かつ  "Lines to scroll at a time" -> 2以上
   - マウスホイールは上下キーを複数回送出 (一度に来る (flush) を挟まずに？) されるので区別可能、inkの実装変更もなしで一応取れるが、モンキーパッチ的。他にも似たようなことはしているので、依然としてnotios開発者には依存のバージョン上げは今後も慎重にしてもらうという前提のもとで実装可能
-  "Roll the mouse wheel to scroll" -> "One screen at a time"
    - マウスホイールはScr up/down を送出 (区別方法なし)

2個目のパターン向けの実装ができそう。1,3個目もwindows側かnotios側で、別に設定すれば良い。

SHIFT + Wheel は Scr up/down を送出するようなので、マウスホイールのみで左右移動もやりたいという場合は以下の設定でできるようになりそう。


```
// ...
      'inspect-proc': {
        ...x.v1.keymappings["inspect-proc"],

        "scroll-left-word": [{
          type: 'special',
          special: 'pageDown',
        }],
        "scroll-right-word": [{
          type: 'special',
          special: 'pageUp',
        }],

        "scroll-down-half-page": [
          ...x.v1.keymappings["inspect-proc"]["scroll-down-half-page"].filter(e => !(e.type === 'special' && e.special === 'pageDown')),
        ],
        "scroll-up-half-page": [
          ...x.v1.keymappings["inspect-proc"]["scroll-up-half-page"].filter(e => !(e.type === 'special' && e.special === 'pageUp')),
        ],
      },
// ...
```

**Comment by LumaKernel** [comment]
https://github.com/frouriojs/notios/pull/92 でマウスホイールサポートをしました。
残念ながらWindowsでは原理的に対応が無理そうです。VSCode経由やminttyも試してみましたが無理そうでした。
cmdやpowershellに関しては確実に無理なのだと思います。minttyのようなその他のターミナルであればもしかしたら対応可能なターミナルも存在しているかもしれません。（それでも中身がcmdやpowershellだと無理かと思われます）

vimでそもそも可能かというのを調べてみましたが、こちらもどうやら厳しそうでした。

Windows上のVSCodeでもWSLに繋げばマウスホイールできました（ただ、SHIFT+マウスホイールは無理でした）
